### PR TITLE
Change file structure

### PR DESCRIPTION
**Pull request by CyrineG**
**Description**

This Draft PR is an example of file structure changes needed to fix the integration with Discuss issue.

**Notes for Reviewers**

Discourse, and rails in general, are very particular about file names and file structure. According to the [developer's guide](https://meta.discourse.org/t/developer-s-guide-to-discourse-themes/93648) this is the expected file structure for a theme component:

    about.json (required)

    common/common.scss  //common file for all css
    common/header.html  //for html  (including script tags).  Anything you add here is inserted at the top of the <body> tag before the Discourse Header
    common/after_header.html //anything you add here will be inserted below the Discourse header but above the rest of the page content
    common/footer.html //anything added here will be inserted just after the end of the page content or just below the <div id="main-outlet"> close tag
    common/head_tag.html  //Anything you add here is inserted just before the close tag of the <head> close tag or </head>
    common/body_tag.html //Anything you add is inserted at the very bottom of the <body> tag
    common/embedded.scss //whatever you add here is only applied to Discourse when it’s embedded on another site.

That's why the html and css files, in this plugin, should be under a `/common` directory. For the javascript file too, in order for the scripts to get triggered they need to be included in either `/common/header.js`, `common/header.js` or `common/body.js` otherwise it won't get triggered. More details are available in the [developer's guide](https://meta.discourse.org/t/developer-s-guide-to-discourse-themes/93648).

In this draft PR, I went ahead and changed part of the file structure. After installing this as theme component I got this display:
image

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
Interesting...but looking at the screenshot it seems a lot of work is yet to be done for the leaderboard to actually start working 🤔

**Comment by CyrineG** [comment]
@Nikhil-Ladha, yes I only moved two files. The whole file structure will need to be changed. I was asked by @kayceeDev to help him figure out why the plugin isn't integrating as expected with Discuss. And I made this draft PR to give the full details of my findings.

**Comment by kayceeDev** [comment]
@CyrineG , Where do we go from here? Can you continue working on this since you understand how discourse works so well? This is vital to community growth and to creating more engagements. I will support and work with you where you see fit. The leaderboard will make sure people who help others are recognized and celebrated for as long as they continue their support and mentorship to fellow contributors. Help is needed here.

**Comment by CyrineG** [comment]
@kayceeDev Allright I'll be happy to help! Next step, I think we need to order the existing code under the file structure indicated in the developper guide (for example: move all assets under a /assets directory).

I haven't had time to look in depth into the leaderboard code yet, but as soon as I can I'll try to apply the correct file structure to all the files and we'll see if that's enough to get the plugin ready to go.

**Comment by kayceeDev** [comment]
Music to my ears. Thank you @CyrineG. Lets get this done then.

**Comment by CyrineG** [comment]
To keep you all updated, I'm afraid I won't be able to look into this till after next week. But I'll definitely come back to it.

**Comment by leecalcote** [comment]
> To keep you all updated, I'm afraid I won't be able to look into this till after next week. But I'll definitely come back to it.

Thank you for setting expectations, @CyrineG.

**Comment by CyrineG** [comment]
@Nikhil-Ladha @kayceeDev is there a reason why you chose to implement this as a theme components instead of as a widget?

**Comment by kayceeDev** [comment]
@CyrineG honestly, anyone you think is better will be ok. At some point I didn't really know if theme components was more preferred to widget. Just do your thing.

**Comment by CyrineG** [comment]
Hello so here's what I've got so far 
image

Since I get CORS errors when I try to access the API for data, I used an exemple of the expected data here. 

The biggest issue i've run into is positioning the LeaderBoard. The way theme components are implemented and integrated in Discourse instances, the js and html code need to be under `/common/head_tag` , `/common/header` (will appear on top of header like in the screenshot) or` /common/body_tag` (will appear at the end of the body tag). The header position is probably not good, and I'm not sure if positioning the leaderboard at the end of the body fits with the expected page design.

Implementing the leaderboard as a widget will allow us to chose where to exactly position it, but that could also mean completely rewriting the plugin to fit the new implementation.

Concerning the "allUsers" page, (in the screenshot I displayed both tables together for testing purposes) adding a new page using a custom page is not possible ([source](https://meta.discourse.org/t/create-a-custom-page-with-theme-cli/209207/2)). Neither is creating files, since a theme component is a front-end component (hence I used localStorage to save the userData). 
 
Note: I'm not a front-end dev so there might be things that i'm missing here.

**Comment by kamalbuilds** [comment]
I am reopening as I think this is a WIP .

**Pull request closed without merging**
